name: CI
on:
  pull_request: {}
  push:
    branches:
      - main
      - '*.*.x'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  CARGO_INCREMENTAL: 0

jobs:
  
  ppc64le:
    runs-on: ubuntu-24.04-ppc64le
    container: ghcr.io/sandeepgupta12/cryptography-runner-ubuntu-24.04:ppc64le
    name: "ppc64le - tests (Python 3.12)"
    env:
      RUSTUP_HOME: /root/.rustup
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0
          submodules: recursive
      # - name: Cache rust and pip
      #   uses: ./.github/actions/cache
      #   timeout-minutes: 2
      #   with:
      #     key: ubuntu-local

      - name: Clone test vectors
        timeout-minutes: 2
        uses: ./.github/actions/fetch-vectors
      # When run in a docker container the home directory doesn't have the same owner as the
      # apparent user so pip refuses to create a cache dir
      # - name: create pip cache dir
      #   run: mkdir -p "${HOME}/.cache/pip"

      - run: /venv/bin/python -m pip install -c ci-constraints-requirements.txt 'nox[uv]' 'tomli; python_version < "3.11"'
      - run: '/venv/bin/nox -v --install-only'
        env:  
          NOXSESSION: tests

      - run: '/venv/bin/nox --no-install --  --color=yes --wycheproof-root="wycheproof" --x509-limbo-root="x509-limbo"'
        env:
          NOXSESSION: tests
          